name: "NextJS Cache"
description: "Cache Next.js for faster application rebuilds."
author: "jongwooo <jongwooo.han@gmail.com>"

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.next/cache
        key: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/pnpm-lock.yaml')) }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/npm-shrinkwrap.json', '**/yarn.lock', '**/pnpm-lock.yaml') }}
branding:
  icon: "archive"
  color: "black"
