name: Check commit messages

on: pull_request

jobs:
  check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR commit messages
        run: |
          curl -s ${{ github.event.pull_request.commits_url }} |
            jq --raw-output '.[].sha' |
            xargs ./.github/scripts/check-commit-messages.sh
